#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export KICKASS_CRYPTO_NAME='kickass-crypto';
export KICKASS_CRYPTO_CODE='kickass-crypto';

export KICKASS_CRYPTO_VERSION='0.2.3';
export KICKASS_CRYPTO_VERSION_MAJOR='0';
export KICKASS_CRYPTO_VERSION_MINOR='2';
export KICKASS_CRYPTO_VERSION_PATCH='3';

export KICKASS_CRYPTO_SVN_DATE='Date: 2024-11-06 00:10:41 +1100 (Wed, 06 Nov 2024)';
export KICKASS_CRYPTO_SVN_REVISION='Revision: 127731528';
export KICKASS_CRYPTO_SVN_AUTHOR='Author: jj5';

export KICKASS_CRYPTO_GIT_DATE='2024-11-06 00:10:41 +1100 (Wed, 06 Nov 2024)';
