#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export _NAME='kickass-crypto';
export _CODE='kickass-crypto';

export _VERSION='0.2.3';
export _VERSION_MAJOR='0';
export _VERSION_MINOR='2';
export _VERSION_PATCH='3';

export _SVN_DATE='Date: 2024-11-05 23:45:00 +1100 (Tue, 05 Nov 2024)';
export _SVN_REVISION='Revision: 196407058';
export _SVN_AUTHOR='Author: jj5';

export _GIT_DATE='2024-11-05 23:45:00 +1100 (Tue, 05 Nov 2024)';
