<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'KICKASS_CRYPTO_NAME', 'kickass-crypto' );
define( 'KICKASS_CRYPTO_CODE', 'kickass-crypto' );

define( 'KICKASS_CRYPTO_VERSION_MAJOR', 0 );
define( 'KICKASS_CRYPTO_VERSION_MINOR', 2 );
define( 'KICKASS_CRYPTO_VERSION_PATCH', 1 );

define(
  'KICKASS_CRYPTO_SVN_DATE',
  '$Date: 2024-11-05 23:49:47 +1100 (Tue, 05 Nov 2024) $'
);
define( 'KICKASS_CRYPTO_SVN_REVISION', '$Revision: 1 $' );
define( 'KICKASS_CRYPTO_SVN_AUTHOR', '$Author: jj5 $' );

define( 'KICKASS_CRYPTO_GIT_DATE', '2024-11-05 23:49:47 +1100 (Tue, 05 Nov 2024)' );
