<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( '_NAME', 'kickass-crypto' );
define( '_CODE', 'kickass-crypto' );

//define( '_VERSION', '0.2.3' );
define( '_VERSION_MAJOR', 0 );
define( '_VERSION_MINOR', 2 );
define( '_VERSION_PATCH', 3 );

define(
  '_SVN_DATE',
  '$Date: 2024-11-05 23:45:00 +1100 (Tue, 05 Nov 2024) $'
);
define( '_SVN_REVISION', '$Revision: 196407058 $' );
define( '_SVN_AUTHOR', '$Author: jj5 $' );

define( '_GIT_DATE', '2024-11-05 23:45:00 +1100 (Tue, 05 Nov 2024)' );
